#!/bin/bash

# This script is for our first assignment, create a system report. #
# Started on October 9th, 2024 by Steven Kouzoukas. #
# echo "System report generated by $USER, on $(date)."

# Place date into variables #
myusername="$USER"
currentdatetime="$(date)"
myhost="$HOSTNAME"
systemuptime=$(uptime -p)
mycpu=$(sudo lshw -C cpu | grep -i product | awk -F: '{print $2}')

# this command doesn't seem to be perfect, but it's the closest I was able to get currently. #
mycpuSpeed=$(sudo dmesg | grep 'MHz' | head -n 1)

myRAM=$(grep MemTotal /proc/meminfo | awk '{print $2/1024 " MB"}')
myDisks=$(lsblk -o NAME,MODEL,SIZE,TYPE | grep -E 'disk|rom' | awk '{print $1, $2, $3}' | paste -sd ',')
myVideoCard=$(lspci | grep -E 'VGA|3D|Display')
myFDQN=$(hostname --fqdn)
myHostAddress=$(host $(hostname))
myGatewayIP=$(ip route | grep default | awk '{print $1, $2,  $3}')
myDNS=$(nmcli dev show | grep 'IP4.DNS' | awk '{print $1, $2}')
myInterfaceName=$(sudo lshw -class network | grep -E 'logical name|product|vendor')
myCidrAddress=$(ip -o -f inet addr show | awk '/scope global/ {print $4}')
myCurrentUsers=$(users | tr ' ' ',')
myhardDrive=$(df -h | grep '^/' | awk '{print $1, $2}')
myProcessCount=$(ps -e | wc -l)
myLoadAverages=$(uptime | awk '{print $6, $7, $8,$9,$10}')
myDataAllocation=$(free -h)
myListeningPorts=$(sudo ss -tuln)
myUFWRules=$(sudo ufw status numbered)
# grabbing the distro name and version from /etc/os-release for easy access. #
#If a distro doesn't have this file, it won't work :( #
source /etc/os-release
mydistro="$PRETTY_NAME"

### Create the report itself from a template.
cat <<EOF

System report generated by $myusername, on $currentdatetime.

System Information
------------------
Hostname: $myhost
OS: $mydistro
Uptime: $systemuptime

Hardware Information
--------------------
cpu:$mycpu
Speed: $mycpuSpeed
Ram: $myRAM
Disk(s): $myDisks
Video: $myVideoCard

Network Information
-------------------
FQDN: $myFDQN
Host Address: $myHostAddress
Gateway IP: $myGatewayIP
DNS Server: $myDNS

InterfaceName:
$myInterfaceName
IP Address: $myCidrAddress

System Status
-------------
Users Logged In: $myCurrentUsers
Disk Space: $myhardDrive
Process Count: $myProcessCount
Load Averages: $myLoadAverages
Memory Allocation:
$myDataAllocation
Listening Network Ports: $myListeningPorts
UFW Rules:
$myUFWRules

EOF
