#!/bin/bash

# This script is for our first assignment, create a system report. #
# Started on October 9th, 2024 by Steven Kouzoukas. #
# echo "System report generated by $USER, on $(date)."

# Place date into variables #
myusername="$USER"
currentdatetime="$(date)"
myhost="$HOSTNAME"
systemuptime=$(uptime -p)
mycpu=$(sudo lshw -C cpu | grep -i product | awk -F: '{print $2}')

# this command doesn't seem to be perfect, but it's the closest I was able to get currently. #
mycpuSpeed=$(sudo dmesg | grep 'MHz' | head -n 1)

myRAM=$(grep MemTotal /proc/meminfo | awk '{print $2/1024 " MB"}')
myhardDrive=$(df -h | grep '^/' | awk '{print $1, $2}')

# grabbing the distro name and version from /etc/os-release for easy access. #
#If a distro doesn't have this file, it won't work :( #
source /etc/os-release
mydistro="$PRETTY_NAME"

### Create the report itself from a template.
cat <<EOF

System report generated by $myusername, on $currentdatetime.

System Information
------------------
Hostname: $myhost
OS: $mydistro
Uptime: $systemuptime

Hardware Information
--------------------
cpu:$mycpu
Speed: $mycpuSpeed
Ram: $myRAM
Disk(s): MAKE AND MODEL AND SIZE FOR ALL INSTALLED DISKS
Video: MAKE AND MODEL OF VIDEO CARD

Network Information
-------------------
FQDN: FQDN
Host Address: IP ADDRESS FOR THE HOSTNAME
Gateway IP: GATEWAY ADDRESS
DNS Server: IP OF DNS SERVER

InterfaceName: MAKE AND MODEL OF NETWORK CARD
IP Address: IP Address in CIDR format

System Status
-------------
Users Logged In: USER,USER,USER...
Disk Space: $myhardDrive
Process Count: N
Load Averages: N, N, N
Memory Allocation: DATA FROM FREE
Listening Network Ports: N, N, N, ...
UFW Rules: DATA FROM UFW SHOW

EOF
